First draft of Minipool Rewards Estimator
alwaysbegrowing/gogopool-dashboard pull request #3
Opened 2023-06-08 20:07 UTC by emersoncloud

First iteration on a page to estimate rewards for running a minipool with GoGoPool. 

This first pass has a table that shows GGP rewards based on different collateralization percentages. And a table with existing node operators and their stats. 

Thing I still want to add
- [ ] Input variable amount of GGP collateral
- [ ] Input more than one minipool, and see how max GGP collateral is affected
- [ ] Update Node Op table to reflect newly calculated minipool values
- [ ] Allow users to see and adjust protocol parameters
- [ ] Differentiate investors visually in the table

2023-06-09 18:15 UTC, Namaskar-1F64F approved these changes
Thanks for the PR. All looks good to me.

style wise and functionality I like it. excited to see the new features as well.

thanks for fixing the types 

1. rename percent of all stake (i dunno what it means)
2. collateral perc -> ggp collateralization
3. change addresses to the copyable/clickable emoji versions to keep consistent with the app styling
4. add some description to explain what this does
5. make the investor stand out and call out they are nerfed (make their address a different color and have an antd tooltip that says, investor with reduced rewards or something)

would be happy to get this out and make a follow up as well if it makes sense.

2023-06-09 18:15 UTC, Namaskar-1F64F commented on components/Calculator.tsx
> +  if (!stakers || !minSeconds || !ggpPriceInAVAX) return <Space></Space>;
```suggestion
  if (!stakers || !minSeconds || !ggpPriceInAVAX) return null;
```

Space is for putting spaces between elements

2023-06-09 18:15 UTC, Namaskar-1F64F commented on components/Calculator.tsx
> +  const epoch = BigNumber.from(Math.floor(d.getTime() / 1000));
```suggestion
  const epoch = BigNumber.from(Math.floor(new Date().getTime() / 1000));
```

2023-06-09 18:15 UTC, Namaskar-1F64F commented on components/Calculator.tsx
> +  let tegs = BigNumber.from(0);
what the hell is a `teg`

2023-06-09 18:15 UTC, Namaskar-1F64F commented on components/Calculator.tsx
> +        .mul(BigNumber.from("1500000000000000000"))
use ether's `parseUnits`

2023-06-09 18:15 UTC, Namaskar-1F64F commented on components/Calculator.tsx
> +      if (staker.stakerAddr != "0xFE5200De605AdCB6306F4CDed77f9A8D9FD47127") {
this should be an array of investors and do something like

`INVESTOR_WALLETS.includes(staker.stakerAddr)`

which would be in a function called

`isInvestorWallet(addr)`

2023-06-09 18:15 UTC, Namaskar-1F64F commented on components/Calculator.tsx
> +        <>{`${commify((+formatEther(ggpStake)).toFixed(2))}`}</>
oh my god i've never seen so many symbols this close to each other

2023-06-09 18:15 UTC, Namaskar-1F64F commented on components/Calculator.tsx
> +      collat: "10%",
nit: prefer full names of variables

2023-06-11 16:29 UTC, RusseII requested changes
Could this be combined with the node operator table? 
<img width="833" alt="CleanShot 2023-06-11 at 11 24 08@2x" src="https://github.com/alwaysbegrowing/gogopool-dashboard/assets/15036618/56ab8a7a-11ff-40e0-b009-c3554d45df80">


Also, the GGP to AVAX price seems wrong 
<img width="231" alt="CleanShot 2023-06-11 at 11 27 44@2x" src="https://github.com/alwaysbegrowing/gogopool-dashboard/assets/15036618/4e6302e3-618d-4ac5-bc89-a108eff5a736">

Percent of all stake for the investors is wrong
<img width="782" alt="CleanShot 2023-06-11 at 11 28 13@2x" src="https://github.com/alwaysbegrowing/gogopool-dashboard/assets/15036618/5dba3a4e-fafa-4a7f-b527-abe1a856a22c">

Is the plan to create an ROI calculator with inputs? Similar to https://www.rocketpooltool.com/ ? The current rewards box seems kinda confusing compared to inputting my own values

2023-06-14 15:26 UTC, emersoncloud commented on components/Calculator.tsx
> +  let tegs = BigNumber.from(0);
Total Eligible GGP Staked. I'll work on a better name

2023-07-13 21:34 UTC, jacktrusler commented
Big mongo PR, all of the changes I worked on had to do with the calculator, it's split into 6 files all located in the `src/components/calculator/` folder, and the page is in `src/pages/calculator.tsx`. Most of the calculations and values are determined in `Calculator.tsx`

 
<img width="1347" alt="Screenshot 2023-07-13 at 5 24 44 PM" src="https://github.com/alwaysbegrowing/gogopool-dashboard/assets/89369559/b3f996e1-1f22-45ac-8afd-1292b2c1d7f9">
The main component is the calculator, and it effects the rest of the page with the variables you set. Thats in `YourMinipool.tsx` and `ProtocolSettings.tsx` Protocol settings is that little box at the top that allows you to manually change the GGP price. `YourMinipoolResults.tsx` is self explanatory. 

<img width="1347" alt="Screenshot 2023-07-13 at 5 24 44 PM" src="https://github.com/alwaysbegrowing/gogopool-dashboard/assets/89369559/b3f996e1-1f22-45ac-8afd-1292b2c1d7f9">
The first table is the how the calculator value affects your rewards `RatioRewardsTable.tsx`, the second is retail node operators.

<img width="1328" alt="Screenshot 2023-07-13 at 5 25 05 PM" src="https://github.com/alwaysbegrowing/gogopool-dashboard/assets/89369559/56029004-b7ed-49fb-bec6-7b121b2fbdb7">
And the third is investor node operators, both retail and investors are in `NodeOpRewardTable.tsx`

2023-07-14 15:57 UTC, Namaskar-1F64F approved these changes
https://share.cleanshot.com/jhQw2cVb

i think this is good to merge though. looks good and seems pretty good at all sizes

2023-07-14 17:59 UTC, gatesyp commented
> what does this mean exactly? “In addition you’ll earn $1,145.47 from the current* GGP base APY of 7.50%.
what does ggp base apy mean? the current wording seems v confusing

how about something like
“By running a minipool, you will also earn AVAX staking rewards at the current AVAX network APY of 7.50%, valued at $1,145.47” 





--- 

change to "Effective GGP Stake" (possibly add a tooltip to it, to explain what effective stake means? ) 
<img width="206" alt="CleanShot 2023-07-14 at 12 56 24@2x" src="https://github.com/alwaysbegrowing/gogopool-dashboard/assets/13278417/a43bb867-cdc3-4b10-bb94-60f6f077087c">

---- 


a user was confused what the difference between panopticon and this calculator was. not sure if there is actionable feedback here. 

he also didnt notice the "add your mninipool" checkmark, and didnt know that the "Retail Node Ops" table was showing the FUTURE state of protocol after you sign up. 

i recommend changing the header "Retail Node Ops" to something more descriptive , or maybe adding some flavor text under the header to describe that the below tables show the FUTURE state of protocol

2023-07-14 18:00 UTC, gatesyp commented
also under Investor Node Ops, changethe "GGP Staked" to "Effective GGP Staked"

2023-07-14 18:14 UTC, jacktrusler commented
> “By running a minipool, you will also earn AVAX staking rewards at the current AVAX network APY of 7.50%, valued at $1,145.47”

Not exactly true is the problem, the GGP APY is different than the AVAX network APY for the base rate

2023-07-14 18:25 UTC, gatesyp commented
the main thing is you can see:
1. how much GGP rewards you will get next month
2. estimate of annual earnings
3. compared to not using GGP

mission accomplished


^^ from a user

2023-07-14 20:48 UTC, jacktrusler commented
I pushed some changes: 

- Changed copy for GGP Minipool to say "In addition you'll earn $1,064.94 from the Avalanche Network at an APY of 7.50%".
- General styling cleanup for different screen sizes.
- Headers of table say "monthly" for rewards.
- Fixed most of the feedback from @Namaskar-1F64F

2023-07-14 22:14 UTC, Namaskar-1F64F commented
@jacktrusler  is it supposed to be so 
![Uploading Safari-GoGoPool Dashboard-GreatDay2BeAliveBWDI_5aa77YeS@2x.png…]()

2023-07-14 23:02 UTC, jacktrusler commented
Yea I thought it was too stretched out across the page

2023-07-14 23:03 UTC, merged

2023-07-14 23:04 UTC, Namaskar-1F64F commented
Thanks for the contribution! @emersoncloud @jacktrusler

As first-time contributors, you will receive 3 months of dappling pro, on us. Let's keep growing 🌱🙏